#! /bin/bash
nvcc -o main main.cu tools.cpp kernel.cu -Xcompiler -fopenmp -lcublas -L /usr/local/cuda/lib64
./main ../Data/movielens_tensor.train ../Data/movielens_tensor.test 3 4 50 0.001 0.05 0.01 0.001 0.05 0.01 0
